baseURL = "https://KhoiNguyendes23.github.io/Kant_Nguyen_Networking_Blog/"
languageCode = "vi-vn"
title = "Lập Trình Cùng Kant"
theme = "blowfish"
enableRobotsTXT = true

[pagination]
  pagerSize = 12

[params]
  description = "Blog lập trình mạng (Java/JS) — ngắn gọn, có ví dụ chạy được."
  defaultAppearance = "auto"
  enableCodeCopy = true
  enableSearch = true
  list.showCards = true
  list.groupByYear = true

[params.article]
  toc = true
  readingTime = true
  showDate = true
  showAuthor = true
  related = true
  shareButtons = ["copy","twitter","linkedin"]

[params.author]
  name = "Kant Nguyen"
  headline = "Trải nghiệm và cũng học lập trình với anh chàng sắp tham gia vào thị trường lao động nhé"
  links = [
    { github = "https://github.com/KhoiNguyendes23" }
  ]

[params.kant]
  homeBackground = true
  homeParallax = true
  backgroundSpeed = 0.15

[related]
  threshold = 80
  includeNewer = true
  toLower = true
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 80
  [[related.indices]]
    name = "keywords"
    weight = 50

[markup.highlight]
  style = "github"

[menu]
  [[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url  = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 3
  [[menu.main]]
    name = "Projects"
    url  = "/projects/"
    weight = 4

[outputs]
  home = ["HTML","RSS","JSON"]
