baseURL = "https://KhoiNguyendes23.github.io/Kant_Nguyen_Networking_Blog/"
languageCode = "vi-vn"
title = "Lập Trình Cùng Kant"
theme = "blowfish"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  defaultAppearance = "auto"
  colorScheme = "system"
  dateFormat = "Jan 02, 2006"
  description = "Blog lập trình mạng (Java/JS) — hiện đại, dễ đọc."
  enableCodeCopy = true
  enableSearch = true
  list.showCards = true
  list.groupByYear = true
  article.readingTime = true
  article.license = ""
  article.shareButtons = ["copy","linkedin","twitter"]
  article.showDate = true
  article.showAuthor = true
  article.showBreadcrumbs = true
  article.showDraftLabel = false
  article.related = true
  mainSections = ["posts"]

[menu]
  [[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url  = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 3
  [[menu.main]]
    name = "Projects"
    url  = "/projects/"
    weight = 4

[params.author]
  name = "Kant Nguyen"
  headline = "Trải nghiệm và cũng học lập trình với anh chàng sắp tham gia vào thị trường lao động nhé"
  links = [{ github = "https://github.com/KhoiNguyendes23" }]

[outputs]
  home = ["HTML","RSS","JSON"]
